Repository DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO, pull requests merged in 2023-08, with the labels that each got.

#44 보관함 뷰 로직 수정 완료
  Shoong/Shoong/View/StorageView/StorageView.swift
Labels: 🎨 Design

#46 [Fix] import 수정
  Shoong/Shoong/Interaction/Dart/HapticManager.swift
Labels: bug

#51 인터렉션 선택 뷰 수정
  Shoong/Shoong/ContentView.swift
  Shoong/Shoong/View/InteractionView/InteractionSelectView.swift
  Shoong/Shoong/View/StorageView/StorageView.swift
Labels: 🎨 Design

#54 Feat/#38 feat slingshot interaction 구현하기
  Shoong/Shoong.xcodeproj/project.pbxproj
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/Contents.json
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building1.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building1.imageset/buildingOne@1x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building1.imageset/buildingOne@2x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building1.imageset/buildingOne@3x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building2.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building2.imageset/buildingTwo@1x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building2.imageset/buildingTwo@2x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building2.imageset/buildingTwo@3x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/jiggy.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/jiggy.imageset/jiggy.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/jiggy.imageset/jiggy@2x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/jiggy.imageset/jiggy@3x.png
  Shoong/Shoong/Interaction/SlingShot/SlingShotAssets/DirTestView6.swift
  Shoong/Shoong/Interaction/SlingShot/SlingShotEffectAssets/Assets.xcassets/Contents.json
  Shoong/Shoong/Interaction/SlingShot/SlingShotEffectAssets/Assets.xcassets/Particle Sprite Atlas.spriteatlas/Contents.json
  Shoong/Shoong/Interaction/SlingShot/SlingShotEffectAssets/Assets.xcassets/Particle Sprite Atlas.spriteatlas/bokeh.imageset/Contents.json
  Shoong/Shoong/Interaction/SlingShot/SlingShotEffectAssets/Assets.xcassets/Particle Sprite Atlas.spriteatlas/bokeh.imageset/bokeh.png
  Shoong/Shoong/Interaction/SlingShot/SlingShotEffectAssets/Assets.xcassets/Particle Sprite Atlas.spriteatlas/spark.imageset/Contents.json
  Shoong/Shoong/Interaction/SlingShot/SlingShotEffectAssets/Assets.xcassets/Particle Sprite Atlas.spriteatlas/spark.imageset/spark.png
  Shoong/Shoong/Interaction/SlingShot/SlingShotEffectAssets/BuildingsBrokenSound.mp3
  Shoong/Shoong/Interaction/SlingShot/SlingShotEffectAssets/FireParticle.sks
  Shoong/Shoong/Interaction/SlingShot/SlingShotGameScene.swift
  Shoong/Shoong/Interaction/SlingShot/SlingShotInteraction.swift
  Shoong/Shoong/Interaction/SlingShot/SlingShotView.swift
Labels: 🎨 Design, ✨ Feature

#62 Feat/#48 feat 다트 인터랙션 진입 시 게임 방법 설명 구현
  Shoong/Shoong.xcodeproj/project.pbxproj
  Shoong/Shoong/Interaction/Dart/DartView.swift
  Shoong/Shoong/Interaction/Dart/HowToPlay.swift
Labels: ✨ Feature

#71 [Feat] 날린 횟수 증가시켜서 뷰에 보여주기
  Shoong/Shoong/Interaction/Dart/DartScene.swift
  Shoong/Shoong/Interaction/Dart/DartView.swift
  Shoong/Shoong/Interaction/Dart/ThrownCount.swift
Labels: ✨ Feature

#73 [Feat] 게이지 바 던질 때 마다 변화하게 만들기
  Shoong/Shoong/Interaction/Dart/DartScene.swift
  Shoong/Shoong/Interaction/Dart/GuageBar.swift
Labels: ✨ Feature

#76 인터렉션 뷰 연결 작업
  Shoong/Shoong/Interaction/Dart/DartView.swift
  Shoong/Shoong/View/InteractionView/InteractionSelectView.swift
  Shoong/Shoong/View/TemplateEditorView/TemplatesEditorView.swift
Labels: 🎨 Design

#80 Design/#63 design 볼링 뷰 레이아웃 작업 및 스유로 감싸기
  Shoong/Shoong.xcodeproj/project.pbxproj
  Shoong/Shoong/Assets.xcassets/BowlingAsset/Contents.json
  Shoong/Shoong/Assets.xcassets/BowlingAsset/black_building_01.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/BowlingAsset/black_building_01.imageset/black_building_01.png
  Shoong/Shoong/Assets.xcassets/BowlingAsset/black_building_01.imageset/black_building_01@2x.png
  Shoong/Shoong/Assets.xcassets/BowlingAsset/black_building_01.imageset/black_building_01@3x.png
  Shoong/Shoong/Assets.xcassets/BowlingAsset/jiggy_crouching_00.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/BowlingAsset/jiggy_crouching_00.imageset/jiggy_crouching_00.png
  Shoong/Shoong/Assets.xcassets/BowlingAsset/jiggy_crouching_00.imageset/jiggy_crouching_00@2x.png
  Shoong/Shoong/Assets.xcassets/BowlingAsset/jiggy_crouching_00.imageset/jiggy_crouching_00@3x.png
  Shoong/Shoong/Assets.xcassets/ColorSet/BackGroundColorSet/backGroundBeige.colorset/Contents.json
  Shoong/Shoong/Interaction/Bowling/BowlingAsset/ball.png
  Shoong/Shoong/Interaction/Bowling/BowlingAsset/pin.png
  Shoong/Shoong/Interaction/Bowling/BowlingGameScene.swift
  Shoong/Shoong/Interaction/Bowling/BowlingView.swift
  Shoong/Shoong/View/InteractionView/InteractionSelectView.swift
Labels: 🎨 Design

#85 템플릿 수정 뷰 파일 교체 완료
  Shoong/Shoong.xcodeproj/project.pbxproj
  Shoong/Shoong/Assets.xcassets/TemplateEditViewImageSet/Contents.json
  Shoong/Shoong/Assets.xcassets/TemplateEditViewImageSet/colorSelecter.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/TemplateEditViewImageSet/colorSelecter.imageset/colorSelecter.png
  Shoong/Shoong/Assets.xcassets/TemplateEditViewImageSet/forderImage.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/TemplateEditViewImageSet/forderImage.imageset/forderImage.png
  Shoong/Shoong/ContentView.swift
  Shoong/Shoong/Model/TextBoxModel.swift
  Shoong/Shoong/Model/TextModel.swift
  Shoong/Shoong/ShoongApp.swift
  Shoong/Shoong/View/MainView.swift
  Shoong/Shoong/View/TemplateEditorView/ColorPicker.swift
  Shoong/Shoong/View/TemplateEditorView/SelectedTemplateView.swift
  Shoong/Shoong/View/TemplateEditorView/TemplateEditView.swift
  Shoong/Shoong/View/TemplateEditorView/TemplateEditer.swift
  Shoong/Shoong/View/TemplateEditorView/TemplatesEditorView.swift
  Shoong/Shoong/View/TemplateEditorView/TextColorPickerView.swift
  Shoong/Shoong/View/TemplateEditorView/TextDragGestureView.swift
  Shoong/Shoong/View/TemplateEditorView/TextEditorView.swift
  Shoong/Shoong/ViewModel/TemplateEditViewModel.swift
  Shoong/Shoong/ViewModel/TemplatesEditorViewModel.swift
Labels: 🎨 Design

#90 [Fix] 볼링 border 변경
  Shoong/Shoong/Interaction/Bowling/BowlingGameScene.swift
Labels: bug

#91 메인뷰 디테일 작업 완료
  Shoong/Shoong/Assets.xcassets/ColorSet/FontColorSet/fontWhiteGray.colorset/Contents.json
  Shoong/Shoong/Assets.xcassets/MainViewImageSet/character.imageset/character.png
  Shoong/Shoong/Assets.xcassets/MainViewImageSet/forderImage.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/MainViewImageSet/forderImage.imageset/forderImage.png
  Shoong/Shoong/Assets.xcassets/MainViewImageSet/mountain.imageset/mountain.png
  Shoong/Shoong/Extension+Modifier/Extension+Color.swift
  Shoong/Shoong/View/MainView.swift
Labels: 🎨 Design

#92 82 design 새총 인터랙션 레이아웃 수정
  Shoong/Shoong/Assets.xcassets/ColorSet/PointColorSet/guageOrange.colorset/Contents.json
  Shoong/Shoong/Assets.xcassets/ColorSet/PointColorSet/interactionGray.colorset/Contents.json
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/angry_jiggy.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/angry_jiggy.imageset/angry_jiggy.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/angry_jiggy.imageset/angry_jiggy@2x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/angry_jiggy.imageset/angry_jiggy@3x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building1.imageset/buildingOne@1x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building1.imageset/buildingOne@2x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building1.imageset/buildingOne@3x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building2.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building2.imageset/buildingTwo@1x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building2.imageset/buildingTwo@2x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/building2.imageset/buildingTwo@3x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/jiggy.imageset/Contents.json
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/jiggy.imageset/jiggy.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/jiggy.imageset/jiggy@2x.png
  Shoong/Shoong/Assets.xcassets/SlingShotAssets/jiggy.imageset/jiggy@3x.png
  Shoong/Shoong/Extension+Modifier/Extension+Color.swift
  Shoong/Shoong/Interaction/Dart/GuageBar.swift
  Shoong/Shoong/Interaction/Dart/ThrownCount.swift
  Shoong/Shoong/Interaction/SlingShot/SlingShotGameScene.swift
  Shoong/Shoong/Interaction/SlingShot/SlingShotInteraction.swift
Labels: 🎨 Design

#97 96 design 인터랙션 레이아웃 전체 점검 및 수정
  Shoong/Shoong/Assets.xcassets/ColorSet/FontColorSet/interactionWhiteGray.colorset/Contents.json
  Shoong/Shoong/Extension+Modifier/Extension+Color.swift
  Shoong/Shoong/Interaction/Dart/HowToPlay.swift
  Shoong/Shoong/Interaction/Dart/ThrownCount.swift
  Shoong/Shoong/Interaction/SlingShot/SlingShotGameScene.swift
Labels: 🎨 Design

#98 88 feat 볼링 새총에 햅틱 바꾸기
  Shoong/Shoong/Interaction/Bowling/BowlingGameScene.swift
  Shoong/Shoong/Interaction/SlingShot/SlingShotInteraction.swift
Labels: ✨ Feature

#100 인터렉션 직전까지 플로우 및 디테일 작업
  Shoong/Shoong.xcodeproj/project.pbxproj
  Shoong/Shoong/ContentView.swift
  Shoong/Shoong/CoreData/CoreDataViewModel/CoreDataViewModel.swift
  Shoong/Shoong/ShoongApp.swift
  Shoong/Shoong/View/InteractionView/InteractionCardView.swift
  Shoong/Shoong/View/InteractionView/InteractionSelectView.swift
  Shoong/Shoong/View/MainView.swift
  Shoong/Shoong/View/TemplateCrumpleView/TemplateCrumpleView1.swift
  Shoong/Shoong/View/TemplateCrumpleView/TemplateCrumpleView2.swift
  Shoong/Shoong/View/TemplateCrumpleView/TemplateCrumpleView3.swift
  Shoong/Shoong/View/TemplateCrumpleView/TemplateCrumpleView4.swift
  Shoong/Shoong/View/TemplateEditorView/ColorPicker.swift
  Shoong/Shoong/View/TemplateEditorView/TemplateEditView.swift
  Shoong/Shoong/View/TemplateEditorView/TemplateEditer.swift
  Shoong/Shoong/ViewModel/TemplateSelectViewModel.swift
  Shoong/Shoong/ViewModel/TemplatesEditorViewModel.swift
Labels: 🎨 Design
